### ISSUE TITLE
The user gets logged out when the application process gets terminated..

### ISSUE THREAD

**Issue by denik7770** [pyx/sanic-auth#13]
Is this a desired behaviour?

**Comment by pyx** [comment]
Could you show me some code? The persistence of login status are relying on the session, if it is in-process session, it will go away with the process, but that's not common practice in production.

**Comment by denik7770** [comment]
I am really new to sanic and web frameworks as a whole, so.. 
`session = {}
@app.middleware('request')
async def add_session(request):
    request.ctx.session = session`
`@app.route('/login', methods=['GET', 'POST'])
async def login(request):
    message = ''
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        # for demonstration purpose only, you should use more robust method
        user = await data.getuserbyname(username)
        if user:
            user = User(id=user.id, name=username)
            auth.login_user(request, user)
            return response.redirect('/')
        elif username == 'admin' and password == '1234567':
            # use User proxy in sanic_auth, this should be some ORM model
            # object in production, the default implementation of
            # auth.login_user expects User.id and User.name available
            user = User(id=0, name=username)
            auth.login_user(request, user)
            return response.redirect('/')
        message = 'invalid username or password'
    return response.html(LOGIN_FORM.format(message))`

**Comment by pyx** [comment]
```python
sessionobj = {}
@app.middleware('request')
async def add_session(request):
    request.ctx.session = sessionobj
```
That's what I meant, here, you are using a local dictionary as the session, it will go away as soon as the very process running this code finished. You can use redis (like in your first snippet), but that should be a separate long-running-process, since redis is in-memory too (which means the content will go away as your local in-process session). Other popular persisting session designs are using database or session cookies, etc., you can read how about sessions in many web framework tutorials, not necessary the sanic-specific.

I have an other sanic plugin that implemented signed cookie based session, I am going to make it work on sanic>20.3.0 shortly.

**Comment by denik7770** [comment]
Thank you.

**Comment by denik7770** [comment]
Thank you.
