### ISSUE TITLE
Does sanic auth support perfectly for the multiple workers situation?

### ISSUE THREAD

**Issue by tonyzhangcn** [pyx/sanic-auth#7]
Hi pyx,
I have another issue want your help. I'm trying to use multiple workers(app.run(host="0.0.0.0", port=8000,workers=2,debug=True)) for the my app and using sanic-auth for user authentication, but encountering some issue, it requires me multiple several times login. When I change it to a single worker(host="0.0.0.0", port=8000,debug=True)), the problem solves. Any suggestion on that? Thank you!

**Comment by tonyzhangcn** [comment]
Hi pyx, 
Thank you so much for providing these detailed explanation.Attached below is the code which I was using to check the authentication and without the multiple login issue. But when I change the last line to "app.run(host="0.0.0.0", port=8000,workers=2,debug=True)" then the issue occurs. I googled on the web and many of the results says sanic currently could not share session between multiple workers. So I'm wondering whether there is any possibility that we can handle it in the code side. Thanks again for your patience. 

Tony 

Here is a brief description on what I do in below code.
When anyone access the html pages (say all the pages are in html), if authorized then pass to the page otherwise redirect to login page. If the page is login.html itself it should pass directly, other static resources like css,js etc should pass directly.

```from sanic import Sanic
from Utils.wcl_auth import auth
from sanic_auth import User
#omitted a lot of imports here#

app = Sanic(__name__)

app.static('/css',"./web/css")
app.static('/js',"./web/js")
app.static('/js/plugins/','./web/js/plugin')
app.static('/img',"./web/img")
app.static('/fonts',"./web/fonts")
app.static("/","web")

app.config.AUTH_LOGIN_ENDPOINT='login'
app.config.AUTH_TOKEN_NAME = 'wcl_auth'
app.config.AUTH_LOGIN_URL = 'login.html'
#omitted a lot of blue prints config here#
session = {}
@app.middleware('request')
async def add_session(request):
    request['session'] = session
    req_path = request.path

    if ".html" in req_path:
        if "/login.html" in req_path:
            pass
        else:
            if not request['session']:
                return response.redirect("login.html")

auth.setup(app)

@app.route("/")
@auth.login_required
async def index(request):
    return response.redirect('index.html')

@app.route("login",methods={'POST','GET'})
async def login(request):
    user_name = request.form.get('username')
    password = request.form.get('password')
    ip = request.remote_addr
    result = user_login(user_name,password,ip)
    if result['success'] == 1:
        user = User(id=result['data'].get('admin_id'),name = result['data'].get('admin_username'))
        auth.login_user(request,user)
        return response.redirect('index.html')
    else:
        return response.redirect('/login.html?message='+result['message'])



@app.route('logout')
@auth.login_required
async def logout(request):
    auth.logout_user(request)
    return response.redirect('/login.html')

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000,debug=True)`
```

**Comment by pyx** [comment]
This is what I have guessed.  You are using in-process storage for session, which is never a good thing in any case except exercise.

I should have made it clear that I use `session = {}` in example only because Sanic does not come with built-in session support and how the session is implemented has nothing to do with Sanic-Auth.

When you have only one worker (process), every request will hit that `session` object, so you are fine.  It's a different story when you have more than one workers (processes). Let's say you have two workers (processes), each process will have their individual memory space, that is, their each have their own `session = {}` created. Now imagine worker A handled your login, and set the flag in it's `session`, moments later, you visit another page, and the request is handled by worker B this time, it check it's copy of `session` for authentication token, and there is none, so you are redirected to the login page, that's basically what happened in your case.

That's why for anything other than exercise, especially in production, you should use a real session, be it in-memory based, or persistent-storage based.

For in-memory based session, a popular one is [Redis](https://redis.io/), but any in-memory data stores will do.  They are lightning fast, the disadvantage is data will not be kept after system reboot unless you save the data somehow.

For persistent-storage based session, databases are widely used. [Sqlite](https://www.sqlite.org/) is a good one to get started since it's well tested and usually already been compiled-in in your python installation (try `import sqlite3`).  [PostgreSQL](https://www.postgresql.org/) is another
excellent choice.  Beside relational database, you can also use NoSQL databases, such as MongeDB.

One of the easy-to-use persistent-storage is digitally-signed cookie (to avoid being tempered by user), popularized by Flask, which have that built-in.

Sanic does not have something like that so I wrote an extension [Sanic-CookieSession](https://github.com/pyx/sanic-cookiesession), it's also pip-installble.

BTW, some design suggestion,

- you are not supposed to do those magic in your `add_session` middleware,
  you should make it `add session` only.
- don't check URL (in your case file extension) like that, for URL path that
  required authentication, make a handler decorated with
  `auth.login_required`, or check URL path in a specific `response`
  middleware.

**Comment by pyx** [comment]
I forgot to mention that, you should use asynchronous versions of drivers (python interface) for any of those session implementation (except something self contained, such as my extension Sanic-CookieSession, since you already have all you need, the signed cookie, within your request, no need to wait for outside information), otherwise, your request handler might be blocked (waited until done) and this, depends on the situation, might make Sanic become virtually synchronous.

[Here](https://github.com/timofurrer/awesome-asyncio#database-drivers) is a list of such drivers, keep in mind that async is not yet well known in python land, so don't expect many production-ready solutions right now. You can also roll your own async wrapper if you know how to do it (read python async docs), but that might be too challenging in your case.

**Comment by tonyzhangcn** [comment]
Hi pyx,
Thank you so much for the detailed explanation and the suggestions. I'm a newbie in python and there is a lot to learn. Thanks again!

**Comment by pyx** [comment]
No problem.

The best way to learn python, IMHO, is not learning through making webapps, because depending on your experience, it might be too overwhelming to learn python the language, web development, the web framework you are using at the same time, even more so in the case of asynchronous one.

Learn by reading "Python Cookbook 3rd Edition" by David Beazly, et al., from top to bottom.
Not only you can learn the how-to, but you can also learn to write practical idiomatic (a.k.a beautiful) python.

Then, read "Fluent Python" by Luciano Ramalho, also from top to bottom, to have a very good understanding of python itself (data model, language construct, the design of the language, etc.)

Then, go through [the official standard library reference](https://docs.python.org/3/library/index.html), no need to memorize anything, just have a rough idea what's inside, what problems they solve, so that when you approach a problem, you know if you can use something in stdlib, and where to lookup the details.

Then, trust me, you'll be much more proficient in python than many python programmers you've ever met.

Good luck.

**Comment by tonyzhangcn** [comment]
Hi pyx, 
I cannot find an appropriate word or phrase to express my appreciation to your help and suggestion, but just say Thank you. You are so nice and willing to provide help, wish you all the best.
